wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/training/MS2Former/TanimotoTraining/train.py
    python_version: 3.9.18
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745612142
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.18
      5: 0.17.5
      6: 4.43.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_f1score_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_precision_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_recall_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_f1score_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_precision_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_recall_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_f1score_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_precision_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_recall_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_f1score_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_precision_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_recall_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_f1score_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_precision_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_recall_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_f1score_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_precision_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_recall_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_f1score_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_precision_step
      5: 1
      6:
      - 1
    - 1: chemotype___c_train_recall_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: b1___a___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: b2___a___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: b3___a___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: b4___a___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: b5___a___b_train_recall_step
      5: 1
      6:
      - 1
