wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/training/MS2Former/MLMTraining/train.py
    python_version: 3.9.18
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745611097
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 77
      - 103
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.18
      5: 0.17.5
      6: 4.43.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_accuracy_step
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_f1score_step
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_precision_step
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_recall_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_f1score_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_precision_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_val_recall_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_mz_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: mz_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: mz_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_mz_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: min_nl_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: nl_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: nl_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_base_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: max_nl_dec_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_train_accuracy_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_train_f1score_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_train_precision_epoch
      5: 1
      6:
      - 1
    - 1: intensity_mask___a_train_recall_epoch
      5: 1
      6:
      - 1
